export { accountTable as authAccountTable } from './account/account-table.js';
export { jwksTable as authJwksTable } from './jwks/jwks-table.js';
export { oauthAccessTokenTable as authOauthAccessTokenTable } from './oauth-access-token/oauth-access-token-table.js';
export { oauthClientTable as authOauthClientTable } from './oauth-client/oauth-client-table.js';
export { oauthConsentTable as authOauthConsentTable } from './oauth-consent/oauth-consent-table.js';
export { oauthRefreshTokenTable as authOauthRefreshTokenTable } from './oauth-refresh-token/oauth-refresh-token-table.js';
export { sessionTable as authSessionTable } from './session/session-table.js';
export { userTable as authUserTable } from './user/user-table.js';
export { verificationTable as authVerificationTable } from './verification/verification-table.js';
